import Foundation
import TestKit

// Suite entry point: `swift run LampBoardTests [filter]`.
// The filter is optional and selects by suite or case name.

// First, the instrument. Everything printed after this line is a measurement,
// and a measurement is worth exactly what the measuring device is worth: a
// neutralised `expect` made all of these report success while checking nothing.
Instrument.prove()

let suites: [TestSuite] = [
    PathNormalizerSuite.suite,
    PanelPlacementSuite.suite,
    ClaudeDesktopSuite.suite,
    HookPayloadDecoderSuite.suite,
    CodexContextSuite.suite,
    CodexAdmissionSuite.suite,
    CodexAmberSuite.suite,
    DismissSuite.suite,
    SessionProcessSuite.suite,
    CodexApprovalSuite.suite,
    CodexTrustSuite.suite,
    IDELockParserSuite.suite,
    WorkspaceResolverSuite.suite,
    IDELockLivenessSuite.suite,
    WindowTitleMatcherSuite.suite,
    SessionDeepLinkSuite.suite,
    RelativeTimeSuite.suite,
    RowSummarySuite.suite,
    StateReducerSuite.suite,
    ReducerFixesSuite.suite,
    LivePruningSuite.suite,
    BackgroundTaskSuite.suite,
    OrderingSuite.suite,
    LiveSessionSuite.suite,
    ReconcileSuite.suite,
    StopFailureReasonSuite.suite,
    CompactDurationSuite.suite,
    TrafficLightStateSuite.suite,
    SessionStatusSuite.suite,
    ColumnLayoutSuite.suite,
    MenuBarSuite.suite,
    RowOrderSuite.suite,
    ColumnSlotSuite.suite,
    IDEKindSuite.suite,
    AppleScriptEscapeSuite.suite,
    SubagentSuite.suite,
    AwaitingReleaseSuite.suite,
    RemoteSessionsSuite.suite,
    WaitingSuite.suite,
    AccessTokenSuite.suite,
    SessionsPayloadSuite.suite,
    HTTPRequestParserSuite.suite,
    AccountLimitsSuite.suite,
    HookConfigMergerSuite.suite,
    HookRepairSuite.suite,
    TranscriptDecoderSuite.suite,
    ConversationSuite.suite,
    TranscriptLocatorSuite.suite,
    TranscriptTailSuite.suite,
    DeliveredMessageSuite.suite,
    MailboxSuite.suite,
    MailboxPermissionSuite.suite,
    MailboxDirectorySafetySuite.suite,
    MailboxReapSuite.suite,
    MailboxDisabledSuite.suite,
    MessageDeliverySwitchSuite.suite,
    DictationLocaleSuite.suite,
    DictationAvailabilitySuite.suite,
    MarkdownParserSuite.suite,
    MarkdownSummarySuite.suite,
    TranscriptPreviewSuite.suite,
    RewakeScriptSuite.suite,
    RewakeRegistrationSuite.suite,
    HookScriptBuilderSuite.suite,
    SeatSuite.suite,
    MultiplexerSuite.suite,
    TerminalListingSuite.suite,
    RowNamesSuite.suite,
    RowSessionsSuite.suite,
    OpenFilesSuite.suite,
    PanelMetricsSuite.suite,
    TranscriptActivitySuite.suite,
    CodexSessionMetaSuite.suite,
    CodexSurfaceSuite.suite,
    PanelIssueSuite.suite,
    PermissionWaitSuite.suite,
    TranscriptPathPolicySuite.suite,
    UpdateFeedSuite.suite,
    CommandSuite.suite,
    TunnelRefusalSuite.suite,
    ContextSuite.suite,
]

let filter = CommandLine.arguments.dropFirst().first
exit(TestRunner.runAndReport(suites, filter: filter))
